### PR TITLE
Event object passed to handlers. 

### PR DESCRIPTION
**Pull request by dskvr**
The `on` handlers were not passing the event as expected. Additionally, for my purposes, I needed the ability have my own `onmessage` handler, added one. ~**This is untested**~

### CODE REVIEW

**Comment by jb55** [comment]
ah right, this looks good. just needs rebase

**Comment by dskvr** [comment]
Will rebase and mark ready for review.

**Comment by jb55** [comment]
thanks, it's pushed to npm @ 0.2.4

**Comment by dskvr** [comment]
np

**Pull request closed without merging**
